name: build & deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy python script
      uses: appleboy/ssh-action@v.0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        
        script: |
          mkdir test
          cd test
