name: build & deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy python script
      run:
        script: |
          mkdir test3
          cd test3
